ActionManager : "{795184CF9AD764DB}Configs/System/chimeraInputCommon.conf" {
 Actions {
  Action ADM_AdminUp {
   Type Digital
   InputSource InputSourceValue "{6A44E2C900001003}" {
    Input "keyboard:KC_UP"
    Filter InputFilterDown "{6A44E2C900001004}" {
    }
   }
  }
  Action ADM_AdminDown {
   Type Digital
   InputSource InputSourceValue "{6A44E2C900001005}" {
    Input "keyboard:KC_DOWN"
    Filter InputFilterDown "{6A44E2C900001006}" {
    }
   }
  }
  Action ADM_AdminSelect {
   Type Digital
   InputSource InputSourceValue "{6A44E2C900001007}" {
    Input "keyboard:KC_RETURN"
    Filter InputFilterDown "{6A44E2C900001008}" {
    }
   }
  }
  Action ADM_AdminNextField {
   Type Digital
   InputSource InputSourceValue "{6A44E2C900001009}" {
    Input "keyboard:KC_TAB"
    Filter InputFilterDown "{6A44E2C90000100A}" {
    }
   }
  }
 }
 Contexts {
  ActionContext CharacterGeneralContext {
   ActionRefs +{
    "ADM_AdminUp"
    "ADM_AdminDown"
    "ADM_AdminSelect"
    "ADM_AdminNextField"
   }
  }
 }
}
